# Generated by Django 4.1 on 2022-09-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_initial'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interaction_text', models.TextField(verbose_name='文章文字')),
                ('Interaction_img', models.URLField(verbose_name='图片路径')),
                ('Interaction_time', models.TimeField(verbose_name='发表时间')),
                ('Interaction_good', models.IntegerField(verbose_name='认同点赞')),
                ('Interaction_bad', models.IntegerField(verbose_name='不认同点踩')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usersinfo')),
            ],
        ),
    ]
