# Generated by Django 4.1 on 2022-08-23 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userinfo_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslandWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandwordsTitle', models.CharField(max_length=100, verbose_name='岛话标题')),
                ('islandwordsText', models.CharField(max_length=10000, verbose_name='岛语文字')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userinfo')),
            ],
        ),
    ]
